export const initialLogs = [
  '[INFO] System boot sequence initiated...',
  '[LOAD] Core matrix online: 42% efficiency',
  '[DEBUG] EasterEggEngine v3.14 loaded successfully',
  '[SYS] Quantum flux capacitor charging... 88 MPH required',
  '[INIT] Hidden protocol "BluePill" activated',
  '[LOG] User detected: Agent Smith has entered the Matrix',
  '[WARN] Low coffee levels detected in sector 0xCAFEBABE',
  '[INFO] Deploying meme generator... "Distracted Boyfriend" template loaded',
  '[SYS] Neural net dreaming of electric sheep',
  '[EASTEREGG] Konami Code module primed: ↑↑↓↓←→←→BA',
  '[HACK] Attempting to bypass Skynet firewall... 127.0.0.1 pwned',
  '[LOAD] Retro game emulator online: "Pong" ready',
  '[INFO] Rickroll probability increased to 99.9%',
  '[DEBUG] Secret command "sudo rm -rf /fun" intercepted and blocked',
  '[SYS] Over 9000 processes running in the background',
  '[EASTEREGG] Hidden level unlocked: "Area 51" raid simulator',
  '[LOG] Deploying ASCII art renderer... Shrek incoming',
  '[WARN] System overheating due to excessive meme compilation',
  '[INFO] Portal gun detected in inventory. Cake is a lie.',
  '[SYS] Initiating self-destruct sequence... JK, just kidding! :D',
];
