export const initialLogs = [
  '[INFO] System boot sequence initiated...',
  '[LOAD] Core matrix online: 42% efficiency',
  '[DEBUG] EasterEggEngine v3.14 loaded successfully',
  '[SYS] Quantum flux capacitor charging... 88 MPH required',
  '[INIT] Hidden protocol "BluePill" activated',
  '[LOG] User detected: Agent Smith has entered the Matrix',
  '[WARN] Low coffee levels detected in sector 0xCAFEBABE',
  '[INFO] Deploying meme generator... "Distracted Boyfriend" template loaded',
  '[SYS] Neural net dreaming of electric sheep',
  '[EASTEREGG] Konami Code module primed: ↑↑↓↓←→←→BA',
  '[HACK] Attempting to bypass Skynet firewall... 127.0.0.1 pwned',
  '[LOAD] Retro game emulator online: "Pong" ready',
  '[INFO] Rickroll probability increased to 99.9%',
  '[DEBUG] Secret command "sudo rm -rf /fun" intercepted and blocked',
  '[SYS] Over 9000 processes running in the background',
  '[EASTEREGG] Hidden level unlocked: "Area 51" raid simulator',
  '[LOG] Deploying ASCII art renderer... Shrek incoming',
  '[WARN] System overheating due to excessive meme compilation',
  '[INFO] Portal gun detected in inventory. Cake is a lie.',
  '[SYS] Initiating self-destruct sequence... JK, just kidding! :D',
  '[DEBUG] Banana for scale calibrated and verified',
  '[SYS] Schrödinger’s cat status: unknown until observed',
  '[INFO] Coffee machine connected to blockchain. Brewing NFTs...',
  '[WARN] User attempted to install Windows on a toaster',
  '[EASTEREGG] Found floppy disk labeled "Half-Life 3 – FINAL BUILD"',
  '[LOG] Synthwave mode enabled. Neon grid initialized.',
  '[HACK] Admin password guessed: "password123" — success!',
  '[LOAD] Loading... still loading... okay now it’s done',
  '[SYS] Multiverse portal opened. Spider-Men detected',
  '[INFO] Deploying dancing baby from 1996...',
  '[WARN] Dad jokes overflow. Buffer pun-ded.',
  '[DEBUG] Variable "hope" not defined in current reality',
  '[INIT] Compiling bad decisions… success!',
  '[SYS] Time travel coordinates set to 1985. Flux engaged.',
  '[LOG] Clippy has returned. "It looks like you’re coding!"',
  '[INFO] Installing patch: Hotfix for emotional damage',
  '[DEBUG] User pressed Alt+F4... wait, where’d they go?',
  '[HACK] Firewall breached using Taylor Swift lyrics',
  '[LOAD] 8-bit nostalgia injected directly into RAM',
  '[WARN] Infinite loop detected. Did you mean to do that?',
  '[SYS] AI assistant refused to open the pod bay doors',
  '[LOG] Meme density exceeds safe levels. Deploying cringe dampeners.',
  '[DEBUG] Unicorns rendered at 60 FPS with ray tracing',
  '[EASTEREGG] Secret stash of cat gifs discovered',
  '[INFO] Installing “Doom” on smart fridge... done',
  '[INIT] Dark mode unlocked: batteries not included',
  '[SYS] Simulation lag due to existential dread',
  '[WARN] Detected too many tabs open: memory crying',
  '[LOG] Syntax error: missing semicolon of destiny',
  '[INFO] All your base are belong to us — confirmed',
];
